#include <iostream>
#include <fstream>
#include "CodeGenerator.h"

using namespace std;

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
CodeGen::CodeGen (string filename)
{
	string cppname = filename;
    cppname.replace(cppname.end()-2, cppname.end(), "cpp");
	cfile.open (cppname);
	cfile << "// Autogenerated Scheme to C++ Code\n";
	cfile << "// File: " << cppname << "\n";
	cfile << "#include <iostream>\n";
	cfile << "#include \"Object.h\"\n";
	cfile << "using namespace std;\n\n";

}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
CodeGen::~CodeGen ()
{
	cfile.close();
}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
void CodeGen::WriteCode (int tabs, string code)
{
	for (int t = 0; t < tabs; t++)
		cfile << '\t';
	cfile << code;
}
